'''
This package is part of a repository that is intended to be a submodule to GASpy.
It performs regressions on data generated by GASpy and makes predictions from
those regressions.
'''

__author__ = 'Kevin Tran'
__email__ = 'ktran@andrew.cmu.edu'


# from . import io
# from . import plot
# from . import preprocessor
# from . import regressor
# from . import predict
